'use client';
import { useCallback, useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog';
import { Input } from '@/components/ui/input';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { AlertCircle, ArrowRight, Check, Clock3, ExternalLink, Minus, Pause, Play, Plus, Radio, Settings2, Shield, Volume2 } from 'lucide-react';
import { bucketLabels, cues, defaultSettings, elapsedMs, phaseIndex, phases, reportTypes, type EventSettings } from '@/lib/scenario';
import { bucketLabel, cueLabel, phaseLabel, phaseShort, reportLabel, t, type Language } from '@/lib/i18n';

type Data = {state:{tableCount:number;phase:string;startedAt:number|null;elapsedBeforePause:number;paused:boolean;revision:number;settings:EventSettings};counts:Record<string,number>;totals:Record<string,number>;done:Record<string,number>;ready:Record<string,boolean>;now:number;durationMs:number;elapsedMs:number};
const fmt=(ms:number)=>{const n=Math.ceil(Math.max(0,ms)/1000);return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`};
export function Dashboard({admin,view}: {admin:boolean;view:'public'|'admin'|'settings'}) {
  const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[login,setLogin]=useState(''),[loginError,setLoginError]=useState(''),[authed,setAuthed]=useState(admin),[tick,setTick]=useState(Date.now()),[draftTables,setDraftTables]=useState('8');
  const refresh=useCallback(async()=>{try {const r=await fetch('/api/state',{cache:'no-store'});const j=await r.json() as Data & {error?:string};if(!r.ok)throw new Error(j.error);setData(j);setError('');}catch(e){setError(e instanceof Error?e.message:'Connection lost');}},[]);
  useEffect(()=>{void refresh();const poll=setInterval(()=>void refresh(),5000);const clock=setInterval(()=>setTick(Date.now()),1000);return()=>{clearInterval(poll);clearInterval(clock)}},[refresh]);
  useEffect(()=>{if(data)setDraftTables(String(data.state.tableCount))},[data?.state.tableCount]);
  const send=async(body:Record<string,unknown>)=>{setBusy(true);setError('');try{const r=await fetch('/api/admin/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json() as Data & {error?:string};if(!r.ok)throw new Error(j.error);setData(j);return true;}catch(e){setError(e instanceof Error?e.message:'Could not save');return false;}finally{setBusy(false)}};
  const signIn=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setLoginError('');try{const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({passcode:login})});const j=await r.json() as {error?:string};if(!r.ok)throw new Error(j.error);setAuthed(true);setLogin('');}catch(e){setLoginError(e instanceof Error?e.message:'Sign in failed')}finally{setBusy(false)}};
  const lang:Language=data?.state.settings.language??'en'; const T=(english:string)=>t(lang,english);
  const colorScheme=data?.state.settings.colorScheme??'adventure';
  useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dataset.theme=colorScheme;document.title=lang==='ru'?'Кризис кайдзю · Штаб':'The Kaiju Crisis · House Command'},[lang,colorScheme]);
  const s=data?.state;const lag=data?tick-data.now:0;const used=s?elapsedMs(s,data!.now+lag):0;const remaining=data?Math.max(0,data.durationMs-used):0;
  const currentCues=cues.filter(c=>c.phase===s?.phase);const currentEffects=currentCues.filter(c=>c.effect && data?.done[c.key]);
  const latest=currentCues.filter(c=>data?.done[c.key]).sort((a,b)=>(data!.done[b.key]??0)-(data!.done[a.key]??0))[0];
  const isAdminRoute=view!=='public';
  const isSettingsRoute=view==='settings';
  useEffect(()=>{
    if(!isAdminRoute||!authed) return;
    type MCP = {registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>Promise<unknown>},options:{signal:AbortSignal})=>void|Promise<void>};
    const context=(document as Document & {modelContext?:MCP}).modelContext;
    if(!context?.registerTool) return;
    const lifecycle=new AbortController();
    const tool={
      name:'record_house_report',title:'Record a table report',
      description:'Record or correct one qualifying success for a numbered table in the House GM matrix.',
      inputSchema:{type:'object',properties:{tableNo:{type:'integer',minimum:1,maximum:20},key:{type:'string',enum:reportTypes.map(x=>x.key)},delta:{type:'integer',enum:[-1,1]}},required:['tableNo','key','delta'],additionalProperties:false},
      annotations:{readOnlyHint:false},
      async execute(input:unknown) {
        const x=input as {tableNo:number;key:string;delta:number};
        if(!Number.isInteger(x.tableNo)||!reportTypes.some(t=>t.key===x.key)||![1,-1].includes(x.delta)) throw new Error('Invalid report');
        const r=await fetch('/api/admin/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'report',...x})});
        const result=await r.json() as Data & {error?:string};
        if(!r.ok) throw new Error(result.error||'Report failed');
        setData(result);
        return {tableNo:x.tableNo,report:x.key,count:result.counts[`${x.tableNo}:${x.key}`]??0,totals:result.totals};
      }
    };
    try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
    return()=>lifecycle.abort();
  },[isAdminRoute,authed]);
  return <div className={isAdminRoute?'site admin-site':'site public-site'}>
    <header className="masthead"><div className="brand"><div className="brand-mark" aria-hidden="true">K</div><div><strong>{T('THE KAIJU CRISIS')}</strong><span>{T('HOUSE COMMAND · PATHFINDER SOCIETY')}</span></div></div><nav><a href="/" className={!isAdminRoute?'nav-active':''}>{T('Live display')}</a><a href="/admin" className={isAdminRoute&&!isSettingsRoute?'nav-active':''}>{T('House GM')}</a>{isAdminRoute&&<a href="/admin/settings" className={isSettingsRoute?'nav-active':''}>{T('Settings')}</a>}</nav></header>
    {!data ? <main className="loading"><Radio size={24}/><p>{error?T(error):T('Connecting to the House…')}</p><Button onClick={()=>void refresh()} variant="outline">{T('Retry')}</Button></main> : <>
      {!isAdminRoute&&<div className="event-identity" aria-label={T('Event details')}><div className="event-identity-inner"><div className="event-identity-number"><span>{T('Event#')}</span><strong>{s!.settings.eventNumber||'—'}</strong></div><div className="event-identity-name"><span>{T('Event name')}</span><strong>{s!.settings.eventName||'—'}</strong></div></div></div>}
      <section className="hero">{!isAdminRoute&&<figure className="cover-illustration"><img src="/kaiju-crisis-cover.jpg" alt={T('The Kaiju Crisis adventure cover')} width={1005} height={1305} loading="eager" decoding="async"/></figure>}<div className="hero-left"><div className="eyebrow"><span className="live-dot"/> {T('LIVE EVENT STATUS')} <span className="eyebrow-sep">/</span> {phaseShort(lang,s!.phase)}</div><h1>{phaseLabel(lang,s!.phase)}</h1><p className="hero-context">{s!.phase==='intro'?T('Muster the tables and prepare to begin.'):s!.phase==='conclusion'?T('The adventure has reached its conclusion.'):T('The House is playing through this act.')}</p></div><div className="time-card"><span className="time-label"><Clock3 size={16}/> {s!.paused?T('TIMER PAUSED'):T('TIME REMAINING')}</span><time dateTime={`PT${Math.ceil(remaining/1000)}S`} className={remaining<=300000?'timer urgent':'timer'}>{fmt(remaining)}</time><div className="timer-track"><span style={{width:`${Math.min(100,100*used/data.durationMs)}%`}}/></div><span className="time-foot">{s!.settings.durations[s!.phase]} {T('minute phase')} · {s!.paused?T('held by House GM'):T('shared live clock')}</span></div></section>
      {error&&<div role="alert" className="error-bar"><AlertCircle size={17}/>{T(error)}<button onClick={()=>void refresh()}>{T('Retry')}</button></div>}
      {!isAdminRoute ? <main className="public-main"><section className="broadcast-panel"><div className="panel-label"><span className="section-index">01</span> {T('LATEST HOUSE ANNOUNCEMENT')}</div>{latest?<div className="broadcast-body"><Volume2 size={24}/><p>{cueLabel(lang,latest.key,'text')}</p></div>:<div className="broadcast-empty"><Radio size={22}/><p>{T('Waiting for the next House announcement.')}</p></div>}<div className="broadcast-footer">{s!.settings.displayMessage||T('This display refreshes automatically every few seconds.')}</div></section><section className="effect-panel"><div className="panel-label"><span className="section-index">02</span> {T('SPECIAL EFFECTS IN PLAY')}</div>{currentEffects.length?<div className="effect-list">{currentEffects.map(c=><article className="effect-item" key={c.key}><div className="effect-symbol">✦</div><div><span>{cueLabel(lang,c.key,'label')}</span><h2>{cueLabel(lang,c.key,'effect')}</h2></div></article>)}</div>:<div className="empty-effect"><div className="empty-orbit">✦</div><h2>{T('No special effect active')}</h2><p>{T('House-wide effects will appear here after the House GM announces them.')}</p></div>}</section></main> : !authed ? <main className="login-wrap"><div className="login-card"><div className="login-icon"><Shield size={26}/></div><span className="panel-label">{T('HOUSE GM ACCESS')}</span><h2>{T('Control the event')}</h2><p>{T('Enter the House GM passcode to record reports, manage the clock, and publish announcements.')}</p><form onSubmit={signIn}><label htmlFor="passcode">{T('Passcode')}</label><Input id="passcode" type="password" value={login} onChange={e=>setLogin(e.target.value)} required autoComplete="current-password"/><Button disabled={busy} className="primary-button">{T('Open control desk')} <ArrowRight size={16}/></Button></form>{loginError&&<p role="alert" className="form-error">{T(loginError)}</p>}</div></main> : isSettingsRoute ? <SettingsPanel data={data} busy={busy} send={send} lang={lang}/> : <main className="admin-main">
        <section className="control-strip"><div className="control-title"><span className="panel-label">{T('EVENT CONTROL')}</span><h2>{phaseShort(lang,s!.phase)}</h2><p>{s!.paused?T('Clock held'):T('Clock running')} · {data.state.tableCount} {T('tables')}</p></div><div className="control-actions"><Button variant="outline" disabled={busy} onClick={()=>void send({action:'timer',mode:s!.paused?'resume':'pause'})}>{s!.paused?<Play size={17}/>:<Pause size={17}/>} {s!.paused?T('Start / resume'):T('Pause clock')}</Button>{phaseIndex(s!.phase)<phases.length-1&&<Button className="primary-button" disabled={busy} onClick={()=>void send({action:'phase',phase:phases[phaseIndex(s!.phase)+1].key})}>{T('Begin')} {phaseShort(lang,phases[phaseIndex(s!.phase)+1].key)} <ArrowRight size={17}/></Button>}<Button asChild variant="outline"><a href="/admin/settings"><Settings2 size={17}/> {T('Settings')}</a></Button></div></section>
        <div className="admin-grid"><section className="admin-panel announcements-panel"><div className="panel-heading"><div><span className="panel-label">{T('HOUSE CUES')}</span><h2>{T('Announcements')}</h2></div><span className="count-pill">{currentCues.filter(c=>data.ready[c.key]&&!data.done[c.key]).length} {T('ready')}</span></div><div className="cue-list">{currentCues.length?currentCues.map(c=>{const done=!!data.done[c.key],ready=data.ready[c.key];const trigger=s!.settings.triggers[c.key];const when=[c.factor!==undefined?`${Math.round((trigger.factor??c.factor)*100)}% ${T('of tables')} · ${bucketLabel(lang,c.threshold!)}`:null,c.at!==undefined?`${trigger.at??c.at} ${T('min')}`:null].filter(Boolean).join(` ${T('or')} `);return <article className={`cue ${ready&&!done?'cue-ready':''}`} key={c.key}><div className="cue-top"><span className={done?'status done':ready?'status ready':'status pending'}>{done?T('Announced'):ready?T('Ready'):T('Waiting')}</span><span className="cue-when">{when}</span></div><h3>{cueLabel(lang,c.key,'label')}</h3><p>{cueLabel(lang,c.key,'text')}</p>{c.effect&&<div className="cue-effect">✦ {cueLabel(lang,c.key,'effect')}</div>}<div className="cue-action">{done?<Button variant="ghost" size="sm" disabled={busy} onClick={()=>void send({action:'undoAnnouncement',key:c.key})}>{T('Undo announcement')}</Button>:<Button variant={ready?'default':'outline'} size="sm" className={ready?'primary-button':''} disabled={!ready||busy} onClick={()=>void send({action:'announce',key:c.key})}><Volume2 size={15}/> {T('Mark announced')}</Button>}</div></article>}):<div className="blank">{T('No timed announcements in this phase. Read the scenario introduction or conclusion aloud.')}</div>}</div></section>
        <section className="admin-panel reports-panel"><div className="panel-heading"><div><span className="panel-label">{T('TABLE REPORTS')}</span><h2>{T('Success matrix')}</h2></div><div className="table-config"><label htmlFor="table-count">{T('Tables')}</label><Input id="table-count" type="number" min="1" max="20" value={draftTables} onChange={e=>setDraftTables(e.target.value)}/><Button size="sm" variant="outline" disabled={busy||draftTables===String(s!.tableCount)} onClick={()=>void send({action:'configure',tableCount:Number(draftTables)})}>{T('Set')}</Button></div></div><div className="totals-row">{Object.entries(bucketLabels).map(([key,label])=><div className="total-chip" key={key}><span>{bucketLabel(lang,key)}</span><strong>{data.totals[key]??0}</strong></div>)}</div><Tabs defaultValue="act1" className="reports-tabs"><TabsList className="phase-tabs">{['act1','act2','act3','act4'].map(p=><TabsTrigger value={p} key={p}>{phaseShort(lang,p)}</TabsTrigger>)}</TabsList>{['act1','act2','act3','act4'].map(p=><TabsContent value={p} key={p}><div className="matrix-scroll"><table className="matrix"><thead><tr><th scope="col">{T('Trigger / report')}</th>{Array.from({length:s!.tableCount},(_,i)=><th scope="col" key={i}>T{i+1}</th>)}<th scope="col">{T('House')}</th></tr></thead><tbody>{reportTypes.filter(x=>x.phase===p).map(type=><tr key={type.key}><th scope="row"><strong>{reportLabel(lang,type.key,'title')}</strong><span>{reportLabel(lang,type.key,'trigger')}</span><em>+{type.weight} {bucketLabel(lang,type.bucket)}</em></th>{Array.from({length:s!.tableCount},(_,i)=>{const n=data.counts[`${i+1}:${type.key}`]??0;return <td key={i}><div className="count-control"><button aria-label={`${T('Remove')} ${reportLabel(lang,type.key,'title')} ${T('from table')} ${i+1}`} disabled={busy||n===0} onClick={()=>void send({action:'report',tableNo:i+1,key:type.key,delta:-1})}><Minus size={14}/></button><b>{n}</b><button aria-label={`${T('Add')} ${reportLabel(lang,type.key,'title')} ${T('for table')} ${i+1}`} disabled={busy||(!('repeat' in type)&&n>=1)} onClick={()=>void send({action:'report',tableNo:i+1,key:type.key,delta:1})}><Plus size={14}/></button></div></td>})}<td className="row-total">{Array.from({length:s!.tableCount},(_,i)=>(data.counts[`${i+1}:${type.key}`]??0)*type.weight).reduce((a,b)=>a+b,0)}</td></tr>)}</tbody></table></div></TabsContent>)}</Tabs><p className="matrix-note">{T('Each press records one qualifying report. Repeatable rows accept multiple reports per table; Ildrea’s pact and cultist encounters count as two successes each.')}</p></section></div><footer className="admin-footer"><span><Check size={14}/> {T('Reports and announcements are saved for the whole House.')}</span><a href="/" target="_blank" rel="noreferrer">{T('Open public display')} <ExternalLink size={14}/></a></footer>
      </main>}
    </>}
  </div>
}

function SettingsPanel({data,busy,send,lang}:{data:Data;busy:boolean;send:(body:Record<string,unknown>)=>Promise<boolean>;lang:Language}) {
  const T=(english:string)=>t(lang,english);
  const [draft,setDraft]=useState<EventSettings>(()=>structuredClone(data.state.settings));
  const [tableCount,setTableCount]=useState(String(data.state.tableCount));
  const [phase,setPhase]=useState(data.state.phase);
  const [elapsed,setElapsed]=useState(String(Math.floor(data.elapsedMs/60000)));
  const [notice,setNotice]=useState('');
  const updateDuration=(key:string,value:number)=>setDraft(d=>({...d,durations:{...d.durations,[key]:value}}));
  const updateTrigger=(key:string,field:'at'|'factor',value:number)=>setDraft(d=>({...d,triggers:{...d.triggers,[key]:{...d.triggers[key],[field]:value}}}));
  const save=async()=>{if(await send({action:'settings',settings:draft}))setNotice(t(draft.language,'Settings saved. The public display will update automatically.'));else setNotice('');};
  const setCount=async()=>{if(await send({action:'configure',tableCount:Number(tableCount)}))setNotice(T('Table count saved.'));else setNotice('');};
  const setPosition=async()=>{if(await send({action:'position',phase,elapsedMinutes:Number(elapsed)}))setNotice(T('Phase and clock position updated.'));else setNotice('');};
  const reset=async()=>{
    if(await send({action:'reset'})) {
      setDraft(defaultSettings());
      setTableCount('8');
      setPhase('intro');
      setElapsed('0');
      setNotice(t('en','Event reset to the starting state. Reports and announcements have been cleared.'));
    } else setNotice('');
  };
  return <main className="settings-main">
    <div className="settings-heading"><div><span className="panel-label">{T('HOUSE GM · SETTINGS')}</span><h2>{T('Event settings')}</h2><p>{T('Changes are shared across the House. The printed scenario values are shown as defaults.')}</p></div><a className="settings-back" href="/admin">{T('← Back to control desk')}</a></div>
    {notice&&<div className="settings-notice" role="status"><Check size={17}/>{notice}</div>}
    <div className="settings-grid">
      <section className="admin-panel settings-card"><div className="settings-card-head"><span className="section-index">01</span><h3>{T('House size')}</h3></div><p>{T('Success thresholds scale with the number of tables. Existing reports from removed tables must be cleared first.')}</p><div className="settings-inline"><label htmlFor="settings-tables">{T('Number of tables')}</label><Input id="settings-tables" type="number" min="1" max="20" value={tableCount} onChange={e=>setTableCount(e.target.value)}/><Button disabled={busy||tableCount===String(data.state.tableCount)} onClick={()=>void setCount()} className="primary-button">{T('Save tables')}</Button></div></section>
      <section className="admin-panel settings-card"><div className="settings-card-head"><span className="section-index">02</span><h3>{T('Current phase & clock')}</h3></div><p>{T('Set the phase and minutes already elapsed. This corrects a mistaken transition or synchronizes the timer; it keeps its current paused or running state.')}</p><div className="settings-inline position-controls"><label htmlFor="settings-phase">{T('Phase')}</label><NativeSelect id="settings-phase" value={phase} onChange={e=>setPhase(e.target.value)}>{phases.map(p=><NativeSelectOption key={p.key} value={p.key}>{phaseLabel(lang,p.key)}</NativeSelectOption>)}</NativeSelect><label htmlFor="settings-elapsed">{T('Elapsed minutes')}</label><Input id="settings-elapsed" type="number" min="0" max="240" value={elapsed} onChange={e=>setElapsed(e.target.value)}/><Button disabled={busy} onClick={()=>void setPosition()} variant="outline">{T('Set position')}</Button></div></section>
      <section className="admin-panel settings-card settings-wide"><div className="settings-card-head"><span className="section-index">03</span><h3>{T('Phase lengths')}</h3></div><p>{T('These values drive the shared countdown. Timed announcement cues below have their own minute marks.')}</p><div className="duration-grid">{phases.map(p=><label key={p.key} className="setting-field"><span>{phaseLabel(lang,p.key)}</span><span className="field-input"><Input type="number" min="1" max="240" value={draft.durations[p.key]} onChange={e=>updateDuration(p.key,Number(e.target.value))}/><small>{T('min')}</small></span></label>)}</div></section>
      <section className="admin-panel settings-card settings-wide"><div className="settings-card-head"><span className="section-index">04</span><h3>{T('Announcement triggers')}</h3></div><p>{T('For “or” cues, whichever condition occurs first makes the cue ready. Thresholds are rounded down to whole House successes.')}</p><div className="trigger-list">{cues.map(c=><div className="trigger-row" key={c.key}><div><strong>{cueLabel(lang,c.key,'label')}</strong><span>{phaseShort(lang,c.phase)}{c.threshold?` · ${bucketLabel(lang,c.threshold)} {T('successes')}`:''}</span></div>{c.factor!==undefined&&<label className="trigger-field"><span>{T('House threshold')}</span><span className="field-input"><Input type="number" min="25" max="500" step="1" value={Math.round((draft.triggers[c.key]?.factor??c.factor)*100)} onChange={e=>updateTrigger(c.key,'factor',Number(e.target.value)/100)}/><small>%</small></span></label>}{c.at!==undefined&&<label className="trigger-field"><span>{T('Minute mark')}</span><span className="field-input"><Input type="number" min="0" max="240" value={draft.triggers[c.key]?.at??c.at} onChange={e=>updateTrigger(c.key,'at',Number(e.target.value))}/><small>{T('min')}</small></span></label>}</div>)}</div></section>
      <section className="admin-panel settings-card settings-wide"><div className="settings-card-head"><span className="section-index">05</span><h3>{T('Public display message')}</h3></div><p>{T('Optional short line below the latest House announcement. Leave blank for the automatic refresh note.')}</p><label className="setting-field" htmlFor="display-message"><span>{T('Message · up to 180 characters')}</span><Input id="display-message" maxLength={180} value={draft.displayMessage} onChange={e=>setDraft(d=>({...d,displayMessage:e.target.value}))} placeholder={T('e.g. Table GMs: report your successes promptly.')}/></label></section>
      <section className="admin-panel settings-card settings-wide"><div className="settings-card-head"><span className="section-index">06</span><h3>{T('Event details')}</h3></div><p>{T('Shown at the top of the public display. Leave either field blank until it is assigned.')}</p><div className="event-fields"><label className="setting-field" htmlFor="event-number"><span>{T('Event#')}</span><Input id="event-number" maxLength={40} value={draft.eventNumber} onChange={e=>setDraft(d=>({...d,eventNumber:e.target.value}))}/></label><label className="setting-field" htmlFor="event-name"><span>{T('Event name')}</span><Input id="event-name" maxLength={120} value={draft.eventName} onChange={e=>setDraft(d=>({...d,eventName:e.target.value}))}/></label></div></section>
      <section className="admin-panel settings-card settings-wide"><div className="settings-card-head"><span className="section-index">07</span><h3>{T('Color scheme')}</h3></div><p>{T('Choose the colors used on both the House GM controls and the public display.')}</p><label className="setting-field" htmlFor="settings-color-scheme"><span>{T('Color scheme')}</span><NativeSelect id="settings-color-scheme" value={draft.colorScheme} onChange={e=>setDraft(d=>({...d,colorScheme:e.target.value as EventSettings['colorScheme']}))}><NativeSelectOption value="original">{T('Original')}</NativeSelectOption><NativeSelectOption value="adventure">{T('Adventure')}</NativeSelectOption><NativeSelectOption value="minimal">{T('B&W Minimalist')}</NativeSelectOption></NativeSelect></label></section>
      <section className="admin-panel settings-card settings-wide"><div className="settings-card-head"><span className="section-index">08</span><h3>{T('Language')}</h3></div><p>{T('Choose the language shown on the House GM controls and the public display.')}</p><label className="setting-field" htmlFor="settings-language"><span>{T('Language')}</span><NativeSelect id="settings-language" value={draft.language} onChange={e=>setDraft(d=>({...d,language:e.target.value as Language}))}><NativeSelectOption value="en">{T('English')}</NativeSelectOption><NativeSelectOption value="ru">{T('Russian')}</NativeSelectOption></NativeSelect></label></section>
      <section className="admin-panel settings-card settings-wide reset-card"><div className="settings-card-head"><span className="section-index">09</span><h3>{T('Reset event')}</h3></div><p>{T('Start a new run with 8 tables, the original phase lengths and triggers, Introduction paused at 15:00, and empty reports and announcements.')}</p><AlertDialog><AlertDialogTrigger asChild><Button variant="destructive" disabled={busy}>{T('Reset entire event')}</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{T('Reset the entire House event?')}</AlertDialogTitle><AlertDialogDescription>{T('This clears every table report and announced cue, restores all settings to their scenario defaults, and returns the clock to the paused Introduction. This cannot be undone.')}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{T('Keep current event')}</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={()=>void reset()}>{T('Reset event')}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section>
    </div>
    <div className="settings-savebar"><span>{T('Phase lengths, triggers, event details, color scheme, language, and public message are saved together.')}</span><div><Button variant="outline" disabled={busy} onClick={()=>{setDraft(structuredClone(data.state.settings));setNotice(T('Saved values restored in the form.'))}}>{T('Discard edits')}</Button><Button className="primary-button" disabled={busy} onClick={()=>void save()}>{T('Save settings')}</Button></div></div>
  </main>
}
