import { bucketLabels, cues, phases, reportTypes } from './scenario';
export type Language = 'en'|'ru';
const ui:Record<string,string>={
  'THE KAIJU CRISIS':'КРИЗИС КАЙДЗЮ','HOUSE COMMAND · PATHFINDER SOCIETY':'ШТАБ · ОБЩЕСТВО СЛЕДОПЫТОВ',
  'Live display':'Общий экран','House GM':'Главный ведущий','Settings':'Настройки','Connecting to the House…':'Подключение к штабу…','Retry':'Повторить',
  'The Kaiju Crisis adventure cover':'Обложка приключения «Кризис кайдзю»',
  'LIVE EVENT STATUS':'СТАТУС СОБЫТИЯ','Muster the tables and prepare to begin.':'Соберите игровые столы и подготовьтесь к началу.','The adventure has reached its conclusion.':'Приключение подходит к концу.','The House is playing through this act.':'Все столы проходят этот акт.',
  'TIMER PAUSED':'ТАЙМЕР НА ПАУЗЕ','TIME REMAINING':'ОСТАЛОСЬ ВРЕМЕНИ','minute phase':'минут на этап','held by House GM':'пауза у главного ведущего','shared live clock':'общий таймер',
  'SPECIAL EFFECTS IN PLAY':'ДЕЙСТВУЮЩИЕ ЭФФЕКТЫ','No special effect active':'Сейчас нет особых эффектов','House-wide effects will appear here after the House GM announces them.':'Общие эффекты появятся после объявления главного ведущего.',
  'LATEST HOUSE ANNOUNCEMENT':'ПОСЛЕДНЕЕ ОБЪЯВЛЕНИЕ','Waiting for the next House announcement.':'Ожидается следующее объявление.','This display refreshes automatically every few seconds.':'Экран автоматически обновляется каждые несколько секунд.',
  'HOUSE GM ACCESS':'ДОСТУП ГЛАВНОГО ВЕДУЩЕГО','Control the event':'Управление событием','Enter the House GM passcode to record reports, manage the clock, and publish announcements.':'Введите код главного ведущего для учёта отчётов, управления таймером и объявлений.','Passcode':'Код доступа','Open control desk':'Открыть панель',
  'EVENT CONTROL':'УПРАВЛЕНИЕ СОБЫТИЕМ','Clock held':'Таймер на паузе','Clock running':'Таймер идёт','tables':'столов','Start / resume':'Запустить / продолжить','Pause clock':'Пауза','Begin':'Начать',
  'HOUSE CUES':'СИГНАЛЫ ДЛЯ ВЕДУЩЕГО','Announcements':'Объявления','ready':'готово','Announced':'Объявлено','Ready':'Готово','Waiting':'Ожидание','of tables':'от числа столов','or':'или','min':'мин',
  'Undo announcement':'Отменить объявление','Mark announced':'Отметить объявленным','No timed announcements in this phase. Read the scenario introduction or conclusion aloud.':'В этой части нет объявлений по таймеру. Прочтите вступление или заключение сценария.',
  'TABLE REPORTS':'ОТЧЁТЫ СТОЛОВ','Success matrix':'Таблица успехов','Tables':'Столы','Set':'Задать','Trigger / report':'Условие / отчёт','House':'Итого',
  'Each press records one qualifying report. Repeatable rows accept multiple reports per table; Ildrea’s pact and cultist encounters count as two successes each.':'Каждое нажатие учитывает один подходящий отчёт. Повторяемые задания можно отмечать несколько раз; договор Илдреа и бои с культистами дают по два успеха.',
  'Reports and announcements are saved for the whole House.':'Отчёты и объявления сохраняются для всех столов.','Open public display':'Открыть общий экран',
  'HOUSE GM · SETTINGS':'ГЛАВНЫЙ ВЕДУЩИЙ · НАСТРОЙКИ','Event settings':'Настройки события','Changes are shared across the House. The printed scenario values are shown as defaults.':'Изменения действуют для всех столов. По умолчанию используются значения сценария.','← Back to control desk':'← К панели управления',
  'House size':'Число столов','Success thresholds scale with the number of tables. Existing reports from removed tables must be cleared first.':'Пороги успехов зависят от числа столов. Перед удалением столов нужно очистить их отчёты.','Number of tables':'Количество столов','Save tables':'Сохранить число столов',
  'Current phase & clock':'Текущий этап и таймер','Set the phase and minutes already elapsed. This corrects a mistaken transition or synchronizes the timer; it keeps its current paused or running state.':'Укажите этап и прошедшие минуты. Это исправит ошибочный переход или синхронизирует таймер, сохранив паузу или ход.','Phase':'Этап','Elapsed minutes':'Прошло минут','Set position':'Задать позицию',
  'Phase lengths':'Длительность этапов','These values drive the shared countdown. Timed announcement cues below have their own minute marks.':'Эти значения задают общий обратный отсчёт. Для объявлений ниже указаны отдельные моменты времени.',
  'Announcement triggers':'Условия объявлений','For “or” cues, whichever condition occurs first makes the cue ready. Thresholds are rounded down to whole House successes.':'Если условия соединены «или», объявление готово при первом выполненном условии. Пороги округляются вниз до целого числа успехов.','successes':'успехов','House threshold':'Порог успехов','Minute mark':'На минуте',
  'Public display message':'Сообщение на общем экране','Optional short line below the latest House announcement. Leave blank for the automatic refresh note.':'Короткая строка под последним объявлением. Оставьте пустой для стандартного сообщения об обновлении.','Message · up to 180 characters':'Сообщение · до 180 символов','e.g. Table GMs: report your successes promptly.':'Например: ведущие столов, сообщайте об успехах сразу.',
  'Event details':'Данные события','Event#':'№ события','Event name':'Название события','Shown at the top of the public display. Leave either field blank until it is assigned.':'Показываются в верхней части общего экрана. Поля можно оставить пустыми до назначения.','Language':'Язык','Choose the language shown on the House GM controls and the public display.':'Выберите язык панели главного ведущего и общего экрана.','English':'Английский','Russian':'Русский',
  'Reset event':'Сброс события','Start a new run with 8 tables, the original phase lengths and triggers, Introduction paused at 15:00, and empty reports and announcements.':'Новый запуск: 8 столов, исходные длительности и пороги, вступление на паузе (15:00), пустые отчёты и объявления.','Reset entire event':'Сбросить всё событие','Reset the entire House event?':'Сбросить всё событие?','This clears every table report and announced cue, restores all settings to their scenario defaults, and returns the clock to the paused Introduction. This cannot be undone.':'Все отчёты и объявления будут удалены, настройки вернутся к значениям сценария, а таймер — к началу вступления на паузе. Действие нельзя отменить.','Keep current event':'Сохранить текущую игру',
  'Phase lengths, triggers, event details, color scheme, language, and public message are saved together.':'Длительность, пороги, данные события, цветовая схема, язык и сообщение сохраняются вместе.','Discard edits':'Отменить изменения','Save settings':'Сохранить настройки',
  'Settings saved. The public display will update automatically.':'Настройки сохранены. Общий экран обновится автоматически.','Table count saved.':'Число столов сохранено.','Phase and clock position updated.':'Этап и время обновлены.','Event reset to the starting state. Reports and announcements have been cleared.':'Событие сброшено. Отчёты и объявления очищены.','Saved values restored in the form.':'В форме восстановлены сохранённые значения.',
  'Connection lost':'Связь потеряна','Could not save':'Не удалось сохранить','Sign in failed':'Не удалось войти','Report failed':'Не удалось сохранить отчёт','Invalid report':'Некорректный отчёт',
  'Live event data is temporarily unavailable':'Данные события временно недоступны','Incorrect passcode':'Неверный код доступа','Request rejected':'Запрос отклонён','House GM access required':'Нужен доступ главного ведущего','Invalid request':'Некорректный запрос',
  'Table count must be from 1 to 20':'Число столов должно быть от 1 до 20','Clear reports from the removed tables first':'Сначала очистите отчёты удаляемых столов','Invalid settings':'Некорректные настройки','Phase lengths must be whole minutes from 1 to 240':'Длительность должна быть целым числом минут от 1 до 240','Success thresholds must be 25% to 500%':'Порог успехов должен быть от 25% до 500%','Cue times must be whole minutes from 0 to 240':'Время объявления должно быть целым числом минут от 0 до 240','A cue setting is missing':'Не задано условие объявления','Choose a valid phase and elapsed minute':'Выберите этап и прошедшие минуты','Timer is already in that state':'Таймер уже в этом состоянии','Advance one phase at a time':'Переходите по одному этапу','Invalid announcement':'Некорректное объявление','Announcement trigger has not been reached':'Условие объявления ещё не выполнено','Unknown action':'Неизвестное действие',
  'Remove':'Убрать','Add':'Добавить','from table':'у стола','for table':'для стола',
};
export function t(lang:Language,english:string):string {return lang==='ru'?(ui[english]??english):english;}
const phaseRu:Record<string,string>={intro:'Вступление',act1:'Акт 1 · В поисках королевы многоножек',act2:'Акт 2 · Логово кайдзю',act3:'Акт 3 · Борьба с культом',act4:'Акт 4 · Освобождение кайдзю',conclusion:'Заключение'};
export function phaseLabel(lang:Language,key:string){return lang==='ru'?(phaseRu[key]??key):(phases.find(p=>p.key===key)?.label??key)}
export function phaseShort(lang:Language,key:string){return lang==='ru'?(key==='intro'?'Вступление':key==='conclusion'?'Заключение':`Акт ${key.slice(-1)}`):(key==='intro'?'Introduction':key==='conclusion'?'Conclusion':`Act ${key.slice(-1)}`)}
const bucketRu:Record<string,string>={act1:'Акт 1',act2:'Акт 2',first:'Первый посланник',act3:'Акт 3',second:'Второй посланник',act4:'Акт 4',third:'Третий посланник'};
export function bucketLabel(lang:Language,key:string){return lang==='ru'?(bucketRu[key]??key):bucketLabels[key as keyof typeof bucketLabels]}
const reportRu:Record<string,[string,string]>={
 thistle:['Выживший в лагере','Исцелить Тистла Фута и узнать хотя бы один факт'],shard:['Норы и чудовища','Пережить хотя бы один осколок яда'],tracks:['Следы в песках','Пройти по обоим следам'],dust:['Прибытие к логову','Обезвредить или преодолеть пыль из осколков'],scout:['Разведка логова','Набрать очков разведки не меньше числа персонажей'],bodies:['Остатки добычи Зимибры','Узнать что-либо о телах гуманоидов'],amir:['Первый посланник','Победить Амира Едилова'],crystal:['Созревший урожай','Нарушить процесс кристаллизации'],combust:['Дрожь Зимибры','Обезвредить опасность воспламеняющегося яда'],drum:['Круг барабанщиков','Нарушить обряд'],chaos:['Посеять хаос','Набрать не менее 12 очков хаоса'],amirbag:['Шатёр Амира','Открыть хотя бы одну сумку Амира'],slittent:['Шатёр Перерезанного Горла','Войти в шатёр Перерезанного Горла'],pact:['Шатёр Илдреа','Найти драконий договор'],slit:['Второй посланник','Победить Перерезанное Горло или следующую волну культистов'],cultists:['Зачистка культистов','Победить культистов в столкновении'],dance:['Прервать танец','Разрушить все части ритуала'],yorak:['Танец Йорака','Успокоить Йорака, обезвредив опасность'],ildrea:['Третий посланник','Победить существ в столкновении'],chain:['Освобождение Зимибры','Снять одну цепь (каждая считается отдельно)'],
};
export function reportLabel(lang:Language,key:string,field:'title'|'trigger'){const r=reportTypes.find(x=>x.key===key);return lang==='ru'?(reportRu[key]?.[field==='title'?0:1]??''):(r?.[field]??'')}
const cueRu:Record<string,[string,string,string?]>={
 a1_75:['Причина установлена','Общество узнало, что лагерь разрушила Зимибра.','+1 бонус обстоятельства к проверкам навыков до конца акта 1.'],a1_warn:['Пять минут до акта 2','Зимибра пробуждается. Бёрнт Райс ведёт Общество к её логову. До конца акта 1 осталось пять минут.'],a2_open:['Первый посланник','Тревога зовёт Общество назад. Путь преграждает Амир Едилов. Ведущие столов: начните столкновение с первым посланником.'],a2_warn:['Пять минут до акта 3','На западе поднимается серый дым. До конца акта 2 осталось пять минут.'],a3_100:['Хаос в лагере','Лагерь культистов охвачен хаосом. Следующий успех каждого игрока становится критическим.','Следующий успех каждого игрока становится критическим.'],a3_200:['Культисты нападают друг на друга','Посланники перестали отличать своих от чужих. Все игроки получают +2 бонус обстоятельства к проверкам навыков до конца акта 3.','+2 бонус обстоятельства к проверкам навыков до конца акта 3.'],a3_open:['Второй посланник','Перерезанное Горло приходит в лагерь со своим многоногим спутником. Ведущие столов: начните столкновение со вторым посланником.'],a3_warn:['Пять минут до акта 4','Йорак, Рогатый Гром, приближается к лагерю. До акта 4 осталось пять минут.'],a4_100:['Тюрьма под контролем','Общество теснит культ у темницы Зимибры. Все игроки получают +2 бонус обстоятельства к проверкам навыков до конца акта 4.','+2 бонус обстоятельства к проверкам навыков до конца акта 4.'],a4_open:['Третий посланник','Илдреа зовёт из глубины каньона. Ведущие столов: начните столкновение с третьим посланником.'],a4_warn:['Зимибра вырывается','Зимибра рвёт цепи и стряхивает бамбуковые шунты. До конца акта 4 осталось пять минут.'],
};
export function cueLabel(lang:Language,key:string,field:'label'|'text'|'effect'){const c=cues.find(x=>x.key===key);return lang==='ru'?(cueRu[key]?.[field==='label'?0:field==='text'?1:2]??''):(c?.[field]??'')}
